'use strict';

// Original TJS editorial copy. Reviewed 2026-09-20 against the linked primary sources.
// Categories describe styles, not inventory availability, service promises, or grading guarantees.
const TJS_EDUCATION_GUIDES = {
  cut: {
    title: 'Diamond cut. The art behind the light.',
    kicker: 'The 4 Cs / 01',
    intro: 'Cut describes how a diamond has been fashioned—not simply its outline. Understanding it helps you look beyond a bright photograph and ask better questions about the stone itself.',
    sections: [
      {title: 'Separate shape, style, and quality', text: 'Round, oval, pear, and heart describe familiar outlines. Brilliant and step cuts describe families of facet arrangements. Cut quality asks how successfully a particular stone has been proportioned and finished. A round diamond is not automatically well cut, and an emerald cut is not intended to look like a round brilliant. First decide which kind of appearance you enjoy; then compare stones within that family instead of treating every silhouette as one competition.'},
      {title: 'Three parts of the sparkle', text: 'Brightness describes returning white light. Fire is the appearance of colored flashes as light separates into its spectrum. Scintillation is the changing sparkle and pattern of bright and dark areas as the stone, viewer, or light moves. Brilliance is often used for a diamond’s bright overall appearance. These effects work together: contrast helps flashes become visible. A diamond need not look uniformly white in every frame to be lively, but one glamorous photograph cannot establish its performance.'},
      {title: 'Read the diamond’s architecture', text: 'The table is the broad top facet. The crown rises above the girdle, the perimeter where the upper and lower portions meet. The pavilion extends below it toward the bottom point or culet facet. Their relationships affect the routes light can take. Table size, crown and pavilion angles, total depth, and girdle thickness must be considered together. A single pavilion angle, a shallow profile, or a large-looking table is not a reliable recipe for an attractive stone.'},
      {title: 'Know what a cut grade covers', text: 'GIA’s established overall cut grade for natural diamonds applies to standard round brilliants in the D–Z color range. Its five levels are Excellent, Very Good, Good, Fair, and Poor. The assessment considers brightness, fire, scintillation, weight ratio, durability, polish, and symmetry. Do not extend that system to every fancy shape or equate Excellent polish and symmetry alone with an overall Excellent cut. Read the laboratory and report type: another laboratory or a laboratory-grown assessment may use a different framework.'},
      {title: 'Compare in motion, then in real life', text: 'Ask for footage of the actual diamond turning in more than one lighting environment. Compare stones under similar conditions and at similar image scale; otherwise photography can become the biggest difference. Notice how bright and dark areas change, whether the outline appeals to you, and whether the stone feels lively beyond concentrated display lighting. Check the report and discuss any prominent dark areas with a knowledgeable jeweler. A grade helps narrow your choices, but it does not choose your favorite for you.'},
      {title: 'Use the studio as a starting point', text: 'Our interactive round model lets you rotate the facets and change pavilion proportions. It is an illustration, not a scan of inventory or a physical light-performance test. The Shallower, Reference, and Deeper settings are geometry examples—not Poor, Excellent, or Ideal grades. Explore the side view, return to the real diamond’s measurements and report, then consider color, clarity, and weight alongside the appearance you love.'}
    ],
    related: [{label: 'Explore cut in the 3D studio', href: '#/education?topic=Cut'}, {label: 'Diamond shapes', href: '#/education/shapes'}, {label: 'Read the color guide', href: '#/education/color'}, {label: 'Reports and verification', href: '#/education/reports'}, {label: 'Explore lab-grown diamonds', href: '#/collection/diamonds'}],
    sources: [{label: 'GIA · Cut and its components', url: 'https://4cs.gia.edu/en-us/diamond-cut/'}, {label: 'GIA · Round-brilliant cut grading', url: 'https://www.gia.edu/gia-about/4cs-cut'}, {label: 'GIA · Diamond anatomy', url: 'https://4cs.gia.edu/interactive-4cs/cut/anatomy.html'}, {label: 'IGI · Cut and appearance', url: 'https://www.igi.org/consumer-education/diamond-4cs/diamond-cut/'}]
  },
  color: {
    title: 'Diamond color. Find your kind of white.',
    kicker: 'The 4 Cs / 02',
    intro: 'Color is a quality characteristic, but the look you love is personal. Learn the language first, then compare the actual diamond in the setting and lighting you expect to enjoy.',
    sections: [
      {title: 'Understand the D–Z bands', text: 'The normal color scale moves from D, colorless, toward Z, light color. Its familiar groups are D–F Colorless, G–J Near Colorless, K–M Faint, N–R Very Light, and S–Z Light. A group is not a single grade: G and J belong to the same band but are not interchangeable. These labels describe body color, not clarity or cut. A higher color grade does not, by itself, mean stronger sparkle or a better choice for every design.'},
      {title: 'A laboratory grade is not a screen color', text: 'Grading uses controlled conditions and reference diamonds called masterstones. Everyday viewing is different. Shape, dimensions, faceting, the mounting, surrounding colors, and lighting can affect what you notice. Camera settings and displays add another layer of variation. Our studio deliberately exaggerates tint to explain the bands; its white and yellow illustrations are not calibrated masterstones. You cannot assign a reliable letter grade by comparing a photograph—or a diamond held beside your phone—to these colors.'},
      {title: 'Fancy color follows a different approach', text: 'Fancy-color diamonds are not simply the next shopping tier after near-colorless. Yellow and brown stones with color beyond the normal Z boundary, and diamonds with other qualifying colors, are evaluated through a separate colored-diamond framework. Hue identifies the color family, tone its lightness or darkness, and saturation its strength. N–R and S–Z remain normal-range bands; fancy color does not automatically begin at N. Ask for the actual colored-diamond report and any treatment disclosure rather than relying on a marketing name.'},
      {title: 'Consider metal and fluorescence separately', text: 'Yellow and rose metals can contribute warmth to the overall look; white metals create a different surrounding contrast. There is no universal rule that a particular letter must be paired with one metal. Fluorescence is another characteristic: some diamonds emit visible light when exposed to ultraviolet light. It is not the same as the D–Z body-color grade and should not be treated as automatically good or bad. Examine the individual stone in relevant lighting instead of judging it from that label alone.'},
      {title: 'Check origin, report, and matching stones', text: 'Both natural and laboratory-grown diamonds can show body color. Origin is not a guarantee of a colorless appearance. Review the terminology on the actual report: laboratories and report formats differ, and GIA’s current D-to-Z laboratory-grown service uses an overall Quality Assessment rather than the natural-diamond reporting format. If the design includes side stones, ask to see how the stones look together. Matching is a design judgment as well as a set of grades, especially across different shapes and sizes.'},
      {title: 'Choose with your eyes and your priorities', text: 'Start by deciding whether you prefer a crisp, near-colorless, or intentionally warm look. Compare shortlisted stones together whenever possible, with similar lighting and a neutral background, then revisit your intended metal. Ask what you can genuinely see and whether the price difference matters to you. We do not promise that every G looks like D, or that one band is invisible once set. The right balance is a clearly described stone whose appearance you enjoy.'}
    ],
    related: [{label: 'Explore color in the 3D studio', href: '#/education?topic=Color'}, {label: 'Choose a metal', href: '#/education/metals'}, {label: 'Read the clarity guide', href: '#/education/clarity'}, {label: 'Natural vs. lab-grown', href: '#/education/compare'}, {label: 'Explore lab-grown diamonds', href: '#/collection/diamonds'}],
    sources: [{label: 'GIA · Diamond color', url: 'https://4cs.gia.edu/en-us/diamond-color/'}, {label: 'GIA · D–Z color bands', url: 'https://4cs.gia.edu/en-us/blog/a-guide-to-diamond-color-d-to-z/'}, {label: 'IGI · Color and viewing conditions', url: 'https://www.igi.org/consumer-education/diamond-4cs/diamond-color/'}, {label: 'GIA · Fancy-color diamonds', url: 'https://www.gia.edu/fancy-color-diamond/buyers-guide'}, {label: 'GIA · Fluorescence explained', url: 'https://4cs.gia.edu/interactive-4cs/more-diamond-info/fluorescence.html'}, {label: 'GIA · Current laboratory-grown services', url: 'https://www.gia.edu/gia-website/laboratory-grown-diamond'}]
  },
  clarity: {
    title: 'Diamond clarity. Look closer, choose clearly.',
    kicker: 'The 4 Cs / 03',
    intro: 'A clarity grade describes characteristics within and on a diamond. It helps you compare stones, but it cannot replace seeing how the individual diamond looks and understanding any practical concerns.',
    sections: [
      {title: 'What clarity describes', text: 'Inclusions are internal characteristics, sometimes reaching the surface; blemishes are surface characteristics. They can relate to a diamond’s growth, cutting, or later wear. Natural and laboratory-grown stones can both have them. Clarity is not a test of origin, and laboratory-grown does not mean flawless. Magnification helps a trained grader evaluate these details, but a dramatic close-up should not be mistaken for the view you will see when wearing the jewelry.'},
      {title: 'Six categories, eleven grades', text: 'At 10× magnification, FL means no inclusions or blemishes are visible to a skilled grader. IF means no inclusions are visible, though blemishes may be present. VVS1 and VVS2 describe minute inclusions that are difficult to see. VS1 and VS2 describe minor inclusions observed with effort. SI1 and SI2 have noticeable inclusions. I1, I2, and I3 have obvious inclusions that may affect transparency, brilliance, or durability. These are eleven grades, not six identical steps; within a numbered category, 1 is higher than 2. GIA does not use SI3.'},
      {title: 'Why counting spots does not work', text: 'Graders consider size, number, nature, position, and relief—the contrast a characteristic makes with its surroundings. One conspicuous feature can matter more than several tiny ones. A feature near the center may be easier to notice than one near the edge, and different types of characteristics have different effects. A report plot, when provided, helps locate identifying features; it is not a photograph or a formula where each mark subtracts the same amount from the grade.'},
      {title: '“Eye-clean” needs a viewing context', text: 'Eye-clean is a trade description, not a GIA clarity grade. Ask what the seller means: viewed from which direction, at what distance, and in what lighting? Your eyesight, the stone’s size and faceting, and the location of its characteristics can affect visibility. A VS grade is not a universal promise that nothing can be seen, and an SI grade does not automatically mean an unattractive diamond. Use magnified footage to understand the stone, then assess it at an ordinary viewing distance too.'},
      {title: 'Separate appearance from durability', text: 'Some characteristics mainly influence what you can see; others can raise questions about transparency or vulnerability to damage. Ask a qualified jeweler or gemologist to explain any surface-reaching feature or durability concern for the actual diamond. Do not assume a setting will safely hide every issue. Read report comments and treatment disclosures, since treatments can affect care. There is no universal inclusion count, clarity label, or screenshot that can certify a stone as unbreakable.'},
      {title: 'Use the lesson, then inspect the stone', text: 'Our studio shows enlarged examples of cloud, feather, cavity, crystal, needle, and pinpoint characteristics. Their forms help explain the terminology; they are not exact 10× views or a real stone’s inclusion map. The clarity grade reference is separate: choosing FL, IF, or another category does not change the example or grade the illustrated diamond. A type does not imply a particular grade or occur in every laboratory-grown stone. Compare the actual diamond, its report, and its price before choosing.'}
    ],
    related: [{label: 'Explore clarity in the 3D studio', href: '#/education?topic=Clarity'}, {label: 'Read a diamond report', href: '#/education/reports'}, {label: 'Read the carat guide', href: '#/education/carat'}, {label: 'Care for your jewelry', href: '#/education/care'}, {label: 'Explore lab-grown diamonds', href: '#/collection/diamonds'}],
    sources: [{label: 'GIA · Diamond inclusions defined', url: 'https://4cs.gia.edu/en-us/blog/diamond-inclusions-defined/'}, {label: 'GIA · The clarity scale', url: 'https://4cs.gia.edu/en-us/diamond-clarity/'}, {label: 'GIA · Clarity grades and factors', url: 'https://www.gia.edu/gia-about/4cs-clarity'}, {label: 'GIA · Seven things about clarity', url: 'https://4cs.gia.edu/en-us/blog/seven-things-to-know-about-diamond-clarity/'}, {label: 'IGI · Clarity characteristics', url: 'https://www.igi.org/consumer-education/diamond-4cs/diamond-clarity/'}]
  },
  carat: {
    title: 'Diamond carat. Weight is only the beginning.',
    kicker: 'The 4 Cs / 04',
    intro: 'Carat is easy to compare, but it is not the whole picture. Pair the weight with measurements, cut, and the proportions of your design to understand what you are choosing.',
    sections: [
      {title: 'Know the unit', text: 'One metric carat, abbreviated ct, equals 0.20 grams or 200 milligrams. A carat is divided into 100 points: 0.75 ct is 75 points, and 1.25 ct is one carat and 25 points. These describe weight, not a quality grade. Do not confuse carat with gold karat, the purity measure used in labels such as 14K or 18K in the United States. Ask for the diamond’s stated weight rather than relying on a rounded product nickname.'},
      {title: 'Look at length, width, and depth', text: 'Diamonds of equal weight do not necessarily occupy the same space from above. Shape and proportions change how weight is distributed; a deeper stone may carry more below the outline rather than showing a larger face-up area. Compare the report’s millimeter measurements alongside the weight. An elongated outline can create a different impression from a round one, but no shape guarantees a particular apparent size. Avoid selecting the widest-looking stone without also considering its cut and appearance.'},
      {title: 'Separate center weight from total weight', text: 'A ring’s total carat weight adds the diamonds included in that description; it does not tell you the center diamond’s weight. For example, a 0.90 ct center with 0.25 ct of accent diamonds totals 1.15 ct, but it is not a 1.15 ct center stone. For earrings, ask whether the stated total applies to one earring or the pair. For mixed-gem jewelry, confirm which materials are included rather than assuming every quoted carat is diamond.'},
      {title: 'Price does not move in a straight line', text: 'Doubling weight does not reliably double price. Quality, shape, origin, availability, and the seller’s pricing all matter, and prices can change around popular weight thresholds. Compare current quotes for genuinely similar stones rather than expecting a fixed percentage saving just below a round number. Lab-grown diamonds generally allow more flexibility than comparable natural diamonds within a budget, but individual quotes still vary. Neither a large carat weight nor natural origin is a promise of resale value or future appreciation.'},
      {title: 'Choose the presence, not only the number', text: 'Consider how the stone will look and feel in the whole ring: its outline, setting height, band width, and neighboring stones all belong in the decision. If you can, view a comparable-sized stone on your hand instead of relying entirely on enlarged photographs. A slightly smaller diamond whose appearance you love may serve your design better than extra weight you do not notice. Ask for a clear breakdown of center stone, accents, metal, and setting before approving the final quote.'},
      {title: 'What our size model can—and cannot—show', text: 'The studio scales one round model to compare weight. Choose a preset or enter any positive carat weight, then compare its outline and estimated diameter with the fixed 1.00 ct reference. The estimate uses a 1.00 ct round at 6.5 mm and cube-root scaling with unchanged proportions. The two outlines share a relative scale, but are not life-size. Large entries are fitted to the 3D viewer; its screen size is not a millimeter measurement. Return to the actual report to confirm the dimensions and fit for your setting.'}
    ],
    related: [{label: 'Explore carat in the 3D studio', href: '#/education?topic=Carat'}, {label: 'Read the cut guide', href: '#/education/cut'}, {label: 'Diamond shapes', href: '#/education/shapes'}, {label: 'Ring sizing and fit', href: '#/education/sizing'}, {label: 'Explore lab-grown diamonds', href: '#/collection/diamonds'}],
    sources: [{label: 'GIA · Carat measurement', url: 'https://4cs.gia.edu/en-us/diamond-carat-weight/'}, {label: 'GIA · Size, weight, and total carat weight', url: 'https://4cs.gia.edu/en-us/blog/nine-things-about-diamond-carat-weight-you-need-to-know/'}, {label: 'IGI · Carat weight and apparent size', url: 'https://www.igi.org/consumer-education/diamond-4cs/carat-weight/'}, {label: 'IGI · Laboratory-grown diamond context', url: 'https://www.igi.org/consumer-education/lab-grown-diamonds/'}]
  },
  shapes: {
    title: 'Find your shape.',
    kicker: 'Diamond essentials',
    intro: 'Begin with the silhouette you love. Then compare the individual diamond—not just its shape name.',
    sections: [
      {title: 'Shape is not cut quality', text: 'Shape is the outline seen from above. Facet arrangement and proportions influence how light moves through the diamond. Two stones with the same outline can have very different appearances. Use the Cut lesson to see the distinction.'},
      {title: 'The ten classics', text: 'Round: circular and balanced. Oval: an elongated curve. Pear: rounded at one end, pointed at the other. Marquise: tapered at both ends. Heart: a cleft with a pointed base. Princess: a square, angular look. Cushion: a square or rectangle with softened corners. Emerald: an elongated, clipped-corner step cut. Asscher: a squarer step-cut look. Radiant: clipped corners with brilliant-style faceting.'},
      {title: 'Compare the actual stone', text: 'Look at length and width as well as carat weight. View the diamond turning in several lighting conditions; still photos can hide changes in its light-and-dark pattern. Check pointed corners and the proposed setting together. No outline alone guarantees sparkle, apparent size, or an eye-clean appearance.'},
      {title: 'Antique-inspired, thoughtfully', text: 'An antique-inspired cutting style is not proof that a diamond is old. TJS keeps those future selections separate from the ten classics until the exact cuts and inventory are approved. Save the shape you like, then compare origin, measurements, and the actual report.'}
    ],
    related: [{label: 'Explore cut in 3D', href: '#/education?topic=Cut'}, {label: 'Understand carat weight', href: '#/education?topic=Carat'}, {label: 'Shop classic shapes', href: '#/collection/diamonds'}, {label: 'Antique shapes', href: '#/antique-shapes'}],
    sources: [{label: 'GIA · Diamond shapes and cut styles', url: 'https://4cs.gia.edu/en-us/blog/guide-diamond-shapes-engagement-rings/'}, {label: 'GIA · Diamond quality factors', url: 'https://www.gia.edu/diamond-quality-factor'}]
  },
  engagement: {
    title: 'A ring with your point of view.',
    kicker: 'Engagement rings',
    intro: 'Choose a design you want to wear, then consider the stone, proportions, and practical details together.',
    sections: [
      {title: 'Start with the style', text: 'Solitaire puts one center stone in focus. Pavé adds closely set small stones. Halo frames the center with accent stones; hidden halo places that detail below it, most visible from the side. Three-stone uses a central stone and two companions. Cluster brings several stones together as one design.'},
      {title: 'Make it personal', text: 'Signature is our name for more expressive designs, without implying a limited edition or exclusive rights. Vintage-inspired describes historical design influences, not a promise that the piece is an antique. A design can belong to more than one family—for example, a solitaire with a hidden halo.'},
      {title: 'Look beneath the silhouette', text: 'Style describes the overall design; prongs, a bezel, and other setting methods describe how stones are held. Ask about setting height, exposed points, maintenance, and how a wedding band will sit alongside it. Try the profile as well as the face-up view.'},
      {title: 'Before saying yes', text: 'Confirm the precise diamond dimensions, metal, ring size, and setting compatibility before production. Compare lab-grown and natural origins separately from design: either origin can suit the look you love. Our local ring journey currently saves inspiration; a saved pairing is not a verified fit, final quote, or production order.'}
    ],
    related: [{label: 'Explore engagement rings', href: '#/collection/engagement'}, {label: 'Find your ring size', href: '#/education/sizing'}, {label: 'Choose a metal', href: '#/education/metals'}, {label: 'Natural vs. lab-grown', href: '#/education/compare'}],
    sources: [{label: 'GIA · Ring settings and styles', url: 'https://4cs.gia.edu/en-us/blog/guide-to-ring-settings/'}, {label: 'GIA · Choosing an engagement ring', url: 'https://www.gia.edu/articles/gia-news-research-purchase-diamond-engagement-ring'}]
  },
  wedding: {
    title: 'Made for your every day.',
    kicker: 'Wedding bands',
    intro: 'Start with all wedding bands, then narrow the selection by design. Comfort matters as much as the first impression.',
    sections: [
      {title: 'Choose your circle of light', text: 'Full eternity places stones around the whole band. Half eternity concentrates them across the top portion. Pavé describes closely set small stones; channel-set stones sit between metal walls. These categories can overlap—a half-eternity band may also be channel set.'},
      {title: 'Build a personal stack', text: 'Stackable bands are intended to combine with other rings; check their actual height and contours together. Signature is our expressive-design family. A shaped band may follow the outline of an engagement ring, while a straight band creates a different relationship. A gap is a style choice, not automatically a fault.'},
      {title: 'Check fit, not just size', text: 'Try the whole stack together. Width, inside profile, neighboring settings, and the way the rings move can change comfort. Ask whether stones or prongs will rub against the adjacent ring, and have the combination checked rather than assuming matching metal guarantees a safe fit.'},
      {title: 'Think beyond the wedding day', text: 'Confirm resizing feasibility before purchase, especially for full-eternity and stone-set bands. Ask about the actual band width, metal, stone origin, and total carat weight. A style name or preview image does not establish those specifications. Final availability and service terms belong on the individual product page.'}
    ],
    related: [{label: 'All wedding bands', href: '#/collection/wedding'}, {label: 'Sizing and fit', href: '#/education/sizing'}, {label: 'Jewelry care', href: '#/education/care'}, {label: 'Metal guide', href: '#/education/metals'}],
    sources: [{label: 'Tiffany & Co. · Eternity ring styles', url: 'https://www.tiffany.com/jewelry/eternity-rings/'}, {label: 'GIA · Settings explained', url: 'https://4cs.gia.edu/en-us/blog/guide-to-ring-settings/'}, {label: 'GIA · Ring size considerations', url: 'https://4cs.gia.edu/en-us/blog/how-to-determine-ring-size-tips-and-ring-size-chart/'}]
  },
  metals: {
    title: 'The metal sets the mood.',
    kicker: 'Materials',
    intro: 'Warm, cool, or somewhere between: choose the color you enjoy, then check the alloy and care behind it.',
    sections: [
      {title: 'Yellow, white, and rose gold', text: 'Jewelry gold is mixed with other metals. Yellow gold keeps a warm appearance; rose alloys use copper to create their pink tone. White gold uses whitening alloys and is often rhodium plated. The exact recipe matters, particularly if you have a known metal sensitivity.'},
      {title: 'Understand the numbers', text: 'Gold karat describes purity, not diamond weight: 18K is 18 parts gold out of 24, or 75%; 14K is about 58.3%. Carat, spelled with a c, measures gemstone weight. Neither number alone tells you how well a finished ring is made.'},
      {title: 'Platinum and white gold', text: 'Platinum is naturally white. White gold’s plated finish can wear and may need renewed rhodium over time. Both can show wear; neither should be described as scratch-proof. Compare the finished piece, its weight and feel, and the maintenance expected for that specific alloy.'},
      {title: 'Choose for your life', text: 'Ask for the metal’s stated fineness and allergy information instead of relying on a color name or a blanket hypoallergenic claim. View the diamond in the metal you want: surrounding color can influence its appearance. Product availability, repair suitability, and future refinishing depend on the particular design—not this general guide.'}
    ],
    related: [{label: 'Explore diamond color', href: '#/education?topic=Color'}, {label: 'Ring styles', href: '#/education/engagement'}, {label: 'Care essentials', href: '#/education/care'}, {label: 'Browse fine jewelry', href: '#/collection/jewelry'}],
    sources: [{label: 'GIA · White, yellow, and rose gold', url: 'https://4cs.gia.edu/en-us/blog/buying-guide-white-yellow-rose-gold-engagement-rings/'}, {label: 'GIA · Choosing ring metals', url: 'https://4cs.gia.edu/en-us/blog/engagement-ring-setting-metals/'}, {label: 'GIA · Carat weight', url: 'https://4cs.gia.edu/en-us/diamond-carat-weight/'}]
  },
  sizing: {
    title: 'A fit worth getting right.',
    kicker: 'Ring sizing',
    intro: 'A ring should feel secure and comfortable. The most useful measurement is taken for your finger and your chosen design.',
    sections: [
      {title: 'Start with a jeweler', text: 'Ask for a professional fitting with physical ring gauges. The ring needs to pass over the knuckle without feeling painfully tight once in place. Temperature and time of day can affect finger size, so mention any noticeable changes when being measured.'},
      {title: 'Measure the right ring', text: 'For a surprise, a well-fitting ring can help a jeweler estimate size—but it should be worn on the intended finger and hand. Confirm whether the jeweler is quoting U.S. sizing or another system. Do not assume the same number means the same size in every country.'},
      {title: 'Allow for the design', text: 'Wider bands and several rings worn together can feel tighter than a narrow ring. Try a similar width, and assess the complete stack. Check resizing options before ordering: a full-eternity pattern or intricate stone setting may limit what can be changed later.'},
      {title: 'What this page cannot measure', text: 'An on-screen circle is not life-size unless the display is calibrated. Printed charts can also change scale during printing. TJS does not present the education diamond or any screen illustration as a sizing instrument. Record a professionally confirmed size, the sizing system, and the intended design before approving an order.'}
    ],
    related: [{label: 'Engagement ring guide', href: '#/education/engagement'}, {label: 'Wedding band guide', href: '#/education/wedding'}, {label: 'Custom design brief', href: '#/custom'}],
    sources: [{label: 'GIA · Ring sizing and fit', url: 'https://4cs.gia.edu/en-us/blog/how-to-determine-ring-size-tips-and-ring-size-chart/'}]
  },
  care: {
    title: 'Keep the light in it.',
    kicker: 'Jewelry care',
    intro: 'A little attention helps jewelry look its best. Begin with the materials, treatments, and condition of the actual piece.',
    sections: [
      {title: 'Gentle cleaning first', text: 'For a secure, untreated diamond piece whose other materials allow it, use warm water, mild dish soap, and a very soft clean brush. Rinse over a bowl rather than an open drain, and dry gently with a lint-free cloth. If you are unsure about treatments, glue, or delicate companion stones, ask a jeweler before soaking.'},
      {title: 'Hard does not mean unbreakable', text: 'Diamonds resist scratching but can chip or cleave after a sharp impact. Remove jewelry before heavy lifting, sports, or work where it can strike hard surfaces. Keep it away from household chemicals and chlorine; these can affect metal alloys and other gemstones.'},
      {title: 'Give each piece its space', text: 'Store pieces separately so stones and metal do not rub against one another. Handle a ring by its band when possible. If a stone moves, a prong catches, or a clasp no longer closes securely, stop wearing the piece and arrange an inspection.'},
      {title: 'Know when to ask for help', text: 'Ultrasonic and steam cleaning are not universal home solutions. Loose settings, fractures, treatments, pearls, and some colored stones need different care. Natural and lab-grown diamonds both deserve appropriate protection. This is general guidance—not a free-service, repair, insurance, or warranty promise; TJS service terms remain a separate policy decision.'}
    ],
    related: [{label: 'Know your metal', href: '#/education/metals'}, {label: 'Read a diamond report', href: '#/education/reports'}, {label: 'Natural vs. lab-grown', href: '#/education/compare'}, {label: 'Care and service', href: '#/care'}],
    sources: [{label: 'GIA · Keep your diamond sparkling', url: 'https://www.gia.edu/gia-news-research-secrets-keep-diamond-sparkling'}, {label: 'GIA · Caring for jewelry', url: 'https://www.gia.edu/gia-news-research-tips-caring-jewelry'}, {label: 'GIA · Diamond care and cleaning', url: 'https://www.gia.edu/UK-EN/diamond-care-cleaning'}]
  },
  reports: {
    title: 'Know what you are choosing.',
    kicker: 'Diamond reports',
    intro: 'A laboratory report helps describe a diamond. Read the actual document alongside the stone—not just a marketing badge.',
    sections: [
      {title: 'Begin with identity', text: 'Check the issuing laboratory, report number, date, and whether the stone is natural or laboratory-grown. Read disclosed treatments and comments. Use the laboratory’s own verification service rather than relying only on a seller’s screenshot or the phrase “certified diamond.”'},
      {title: 'Compare like with like', text: 'Review the measurements and weight, then the quality information provided by that report type. Natural diamond reports and laboratory-grown assessments do not all use identical terminology. GIA’s current D-to-Z laboratory-grown service uses a Quality Assessment with Premium or Standard categories; an older report or a different laboratory can have a different format.'},
      {title: 'Read beyond the headline', text: 'Ask which document belongs to the actual stone being sold and have its identifying features checked when needed. A report lookup confirms a record; it does not alone prove that the physical diamond in front of you matches it. Photographs and a viewing appointment can answer appearance questions that specifications cannot.'},
      {title: 'A report is not a price promise', text: 'A grading or assessment report is not an appraisal, insurance policy, resale guarantee, or guarantee of future value. GIA does not provide appraisals. If you need an insurance valuation, ask the insurer what documentation it requires and use a suitably qualified independent appraiser.'}
    ],
    related: [{label: 'Explore the 4 Cs', href: '#/education?topic=Cut'}, {label: 'Clarity explained', href: '#/education?topic=Clarity'}, {label: 'Natural vs. lab-grown', href: '#/education/compare'}, {label: 'Browse lab-grown diamonds', href: '#/collection/diamonds'}],
    sources: [{label: 'GIA · Current laboratory-grown services', url: 'https://www.gia.edu/gia-website/laboratory-grown-diamond'}, {label: 'GIA · Updated laboratory-grown assessment', url: 'https://www.gia.edu/gia-news-press/updated-laboratory-grown-diamond-services-to-launch-october-1'}, {label: 'GIA · Report Check', url: 'https://www.gia.edu/report-check-landing'}, {label: 'GIA · Reports and appraisals', url: 'https://www.gia.edu/FAQ/gia-faq-gia-appraise-diamond'}]
  },
  jewelry: {
    title: 'Build your jewelry wardrobe.',
    kicker: 'Fine jewelry',
    intro: 'Start with the piece you will reach for, then explore its proportions, fastening, and detail. There is no required way to wear it.',
    sections: [
      {title: 'Earrings', text: 'Studs sit at the earlobe. Hoops form a loop; huggies are smaller hoops worn close to the ear. Signature gathers more expressive designs. Look at dimensions, weight, closure type, and whether a listing is a pair or a single earring—not just the photograph.'},
      {title: 'Necklaces', text: 'Solitaire centers on one stone; tennis follows a continuous line of stones. Cross and Letter describe motifs. Bezel and Halo describe how a stone is framed. Signature and Seasonal are design edits, not gemstone quality grades. Choose the necklace first, then use its style bar to narrow the collection.'},
      {title: 'Bracelets', text: 'Explore Tennis, Flex Bangles, Station & Link, and Cuban Link as separate style families. Before purchase, compare the actual length, inner dimensions, movement, and clasp. A flexible-looking photograph is not a measurement or a promise that a piece can be bent freely.'},
      {title: 'The finishing details', text: 'For men’s rings, the intended collection labels are Classic, Bezel, and Bezel Edge; use product photos and specifications to understand the exact construction. Across jewelry, ask whether carat weight describes one stone or all stones combined. Confirm metal and diamond origin, and check care instructions for every material in the piece. Collection names describe the intended range; they do not mean every style is currently stocked.'}
    ],
    related: [{label: 'Earrings', href: '#/collection/earrings'}, {label: 'Necklaces', href: '#/collection/necklaces'}, {label: 'Bracelets', href: '#/collection/bracelets'}, {label: 'Metal and materials', href: '#/education/metals'}, {label: 'Care essentials', href: '#/education/care'}],
    sources: [{label: 'Blue Nile · Stud earrings', url: 'https://www.bluenile.com/jewelry/earrings/stud-earrings'}, {label: 'Blue Nile · Hoop and huggie styles', url: 'https://www.bluenile.com/jewelry/gold-jewelry/gold-earrings'}, {label: 'Tiffany & Co. · Fine jewelry categories', url: 'https://www.tiffany.com/jewelry/'}]
  }
};
