'use strict';
function studioCustomPage(){return `<article class="studio-custom">
<section class="studio-custom-hero"><div><p class="eyebrow">THE CUSTOM STUDIO</p><h1>Your vision.<br><em>Made personal.</em></h1><p>Start with a feeling, a sketch, or a detail you love. Together, we can shape it into a piece that belongs only to you.</p><button class="button" type="button" data-custom-jump>Begin your design ↗</button><a class="text-link" href="#/collection/engagement?build=1">Or build a diamond ring</a></div><figure><img src="assets/custom-story/hero.webp" alt="Diamond stud earrings worn in a Jewelry Studio portrait" width="535" height="515" fetchpriority="high"><figcaption>Inspiration from The Jewelry Studio</figcaption></figure></section>
<section class="studio-process"><p class="eyebrow">A THOUGHTFUL PROCESS</p><h2>From a first thought<br>to your signature piece.</h2><div class="studio-process-grid"><article><span>01</span><h3>Your idea</h3><p>Tell us what you have in mind. Share the occasion, your budget and the shapes or details you keep coming back to.</p></article><article><span>02</span><h3>Your design</h3><p>Refine the stone, metal and proportions. Review a design, itemized quote and agreed terms before production begins.</p></article><article><span>03</span><h3>Your piece</h3><p>Once approved, your design moves through making and final checks. Timing is agreed for your individual project.</p></article></div></section>
<section class="studio-custom-story"><img src="assets/custom-story/craft.webp" alt="A delicate solitaire necklace worn in a Jewelry Studio portrait" width="535" height="515" loading="lazy"><div><p class="eyebrow">BEYOND THE RING</p><h2>A small detail.<br><em>A very personal story.</em></h2><p>A meaningful initial. A favorite silhouette. An everyday piece, made unmistakably yours. Explore ideas for rings, necklaces, earrings and bracelets.</p><button class="text-link" type="button" data-custom-jump>Tell us your idea ↗</button></div></section>
<section class="studio-brief" id="custom-brief"><div><p class="eyebrow">LET’S BEGIN</p><h2>What are you dreaming of?</h2><p>You don’t need a finished design. A few thoughtful details are enough to start the conversation.</p><p class="studio-local-note">Local preview: this form downloads your design brief. It does not send an inquiry. Please use sample contact details for testing.</p><a class="text-link" href="#/policy/custom">Custom order terms · pending review ↗</a></div><div><form id="custom-form" class="form-grid"><label>Your name<input name="name" placeholder="Your name" maxlength="80" required autocomplete="name"></label><label>Email address<input name="email" type="email" placeholder="you@example.com" maxlength="120" required autocomplete="email"></label><label>What are we creating?<select name="piece"><option>Engagement ring</option><option>Wedding band</option><option>Earrings</option><option>Necklace</option><option>Bracelet</option><option>Something else</option></select></label><label>Approximate budget<select name="budget"><option>Let’s discuss</option><option>Under $2,500</option><option>$2,500–$5,000</option><option>$5,000–$10,000</option><option>$10,000+</option></select></label><label>Do you have a stone?<select name="stone"><option>No, help me choose</option><option>Yes, I have my own stone</option></select></label><label>Preferred timing<input name="timing" placeholder="e.g. An anniversary in December" maxlength="150"></label><label class="wide">Tell us your idea<textarea name="idea" placeholder="Shapes, details, inspiration, and what makes it meaningful…" maxlength="2000" required></textarea></label><p class="form-note wide">Customer-supplied stones require inspection, documented ownership, an agreed risk allocation, and a signed work order before acceptance. No coverage or refund terms are promised here.</p><button class="button wide" type="submit">Download my design brief ↓</button><div class="wide" id="custom-status" role="status"></div></form></div></section>
<section class="studio-custom-faq"><p class="eyebrow">A LITTLE CLARITY</p><h2>Before we begin.</h2>${studioFaqItems().slice(0,4).map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section></article>`;}
function studioFaqItems(){return [
 ['Do I need a finished design?','No. A sketch, an inspiration image, a meaningful detail or a simple description gives us a starting point.'],
 ['Can I choose the diamond first?','Yes. Choose a diamond and then a ring design, or begin with the design. Your selections stay together as you browse this local preview.'],
 ['Do you sell the setting on its own?','Our ring-building experience is for complete rings. Select a ring design and its center diamond together; standalone settings are not offered.'],
 ['Can I use a stone I already own?','Tell us about it in your design brief. Acceptance would require inspection and written agreement on suitability, responsibilities and work terms. It is not automatically accepted.'],
 ['How long will a custom piece take?','A project-specific schedule needs to be agreed after the design and materials are reviewed. No fixed production or shipping timeline has been approved yet.'],
 ['Can I return or resize a ring?','Return eligibility, the return window and resizing terms are still being finalized. The policy drafts are not active customer promises. <a href="#/policy/returns">View return policy status.</a>'],
 ['Will Afterpay be available?','Afterpay is planned, but not connected. Available options will depend on merchant setup, market and customer eligibility.'],
 ['Does a purchase currently fund a donation?','The campaign is in development. The Impact counters are draft layout figures, not verified donations or outcomes. Final giving terms and reporting still need approval.']
];}
function studioFaqPage(){
 const topics={returns:'Eligibility, exchanges and the return process.',shipping:'Delivery, tracking and shipping arrangements.',warranty:'Repairs, resizing and care after purchase.',insurance:'Understanding protection for your jewelry.',payments:'Payment methods, offers and financing.',custom:'Design approval, changes and personal details.',privacy:'Your information and how it is handled.',terms:'The terms behind your shopping experience.'};
 return `<article class="studio-help">
 <header class="studio-help-heading"><p class="eyebrow">CLIENT CARE</p><h1>FAQs &amp; policies.</h1><p>A little clarity, at every step. Explore our answers and find the details that matter to you.</p><nav class="studio-help-jumps" aria-label="Client care sections"><button type="button" data-help-jump="help-questions">Common questions <span aria-hidden="true">↓</span></button><button type="button" data-help-jump="help-policies">Browse policies <span aria-hidden="true">↓</span></button><a href="#/contact">Contact the studio <span aria-hidden="true">↗</span></a></nav></header>
 <p class="studio-help-status"><strong>Preview for review.</strong> The policy pages below are drafts, not active customer terms. Final eligibility, fees and timelines will be published after approval.</p>
 <section class="studio-help-policies" id="help-policies" aria-labelledby="help-policies-title"><div class="studio-help-section-title"><div><p class="eyebrow">THE DETAILS, TOGETHER</p><h2 id="help-policies-title">Find your policy.</h2></div><span>8 policy drafts</span></div><div class="studio-policy-grid">${Object.entries(POLICY).map(([key,p])=>`<a class="studio-policy-card" href="#/policy/${key}"><span class="studio-policy-label">For review</span><h3>${p[0]}</h3><p>${topics[key]}</p><span class="studio-policy-action">Read draft <span aria-hidden="true">↗</span></span></a>`).join('')}</div></section>
 <section class="studio-faq studio-help-questions" id="help-questions" aria-labelledby="help-questions-title"><p class="eyebrow">A FEW GOOD QUESTIONS</p><h2 id="help-questions-title">Before you choose.</h2>${studioFaqItems().map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>
 <aside class="studio-help-contact"><div><h2>A question of your own?</h2><p>Find our contact options or prepare a personal design brief.</p></div><a class="button outline" href="#/contact">Contact the studio <span aria-hidden="true">↗</span></a></aside>
 </article>`;
}
document.addEventListener('click',event=>{
 const button=event.target.closest('[data-help-jump]');
 if(!button)return;
 const id=button.dataset.helpJump;
 if(!['help-questions','help-policies'].includes(id))return;
 const target=document.getElementById(id);
 if(target){target.setAttribute('tabindex','-1');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});target.focus({preventScroll:true});}
});
function studioJournalPage(){return `<section class="studio-journal"><p class="eyebrow">THE STUDIO JOURNAL</p><h1>A little knowledge.<br><em>A considered choice.</em></h1><p>Useful reading, without the overwhelm.</p><div class="studio-journal-list">${[['Choosing your diamond','A practical guide to cut, color, clarity and carat.','education','4 Cs'],['Natural or lab-grown?','Understand origin, grading and the choice that suits you.','education/compare','Origin'],['Made to be worn','A thoughtful starting point for caring for your jewelry.','care','Care']].map(([title,copy,route,label],i)=>`<a href="#/${route}"><span class="studio-journal-number">0${i+1}</span><div><small>${label}</small><h2>${title}</h2><p>${copy}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div><p class="studio-local-note">The journal currently connects to your existing guides. New blog topics and the publishing schedule are still to be decided.</p></section>`;}
